Repository dask/helm-chart, pull requests merged in 2020-11, with the labels that each got.

#123 Bump Dask-Gateway to 0.9.0
  daskhub/Chart.yaml
  daskhub/README.md
  daskhub/values.yaml
Labels: chart/daskhub

#137 Expose loadBalancerIP option
  dask/README.md
  dask/templates/dask-scheduler-service.yaml
  dask/values.yaml
Labels: chart/dask

#144 ci: automatically update jupyterhub/dask-gateway chart dependencies
  .github/workflows/watch-dependencies.yml
  .github/workflows/watch-docker-hub.yml
Labels: chart/daskhub, maintenance

#146 ci: fix syntax error in workflow
  .github/workflows/watch-dependencies.yml
Labels: maintenance

#148 Bump chartpress to 1.0.0
  .github/workflows/publish-charts.yml
Labels: maintenance
